name: Checks

on: push

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - name: check formatting
        run: uv run ruff format --check .
      - name: check linting
        run: uv run ruff check .
      - name: check mypy
        run: uv run mypy .

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: tests
        run: uv run pytest --cov -vv .
      - name: upload coverage
        if: matrix.python-version == '3.13'
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: false
